apiVersion: v1
kind: ConfigMap
metadata:
  name: java-app-config
  namespace: mohamed-tamer
data:
  # property-like keys; each key maps to a simple value
  name: "mohamed tamer abdo farh"
  track: "DevOps"
