apiVersion: apps/v1
kind: Deployment
metadata:
    name: java-app
    namespace: mohamed_tamer
    labels:
        app: java-app
        tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name:   java-app
        image: hassaneid/depi-java:v12
        ports:
        - containerPort: 8090
        env:
          - name: my_name
            valueFrom:
              configMapKeyRef:
                name: java-app-config
                key: name
          - name: my_track
            valueFrom:
              configMapKeyRef:
                name: java-app-config
                key: track
        

