apiVersion: v1
kind: Service
metadata:
  name: java-svc
  namespace: mohamed-tamer
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30809
  type: NodePort